// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtR6VKFXGqT9YFIgiJlH-w2PR64gZcd2A',
    appId: '1:57337771510:web:d0dce47aed56b67120c3d7',
    messagingSenderId: '57337771510',
    projectId: 'cmsc23-project-juatco-maiso',
    authDomain: 'cmsc23-project-juatco-maiso.firebaseapp.com',
    storageBucket: 'cmsc23-project-juatco-maiso.appspot.com',
    measurementId: 'G-WM686NMVBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaSD1sLEVtG-hM3bEUQ5P5f4pQ802UUPs',
    appId: '1:57337771510:android:3a07c4fbd13c70a920c3d7',
    messagingSenderId: '57337771510',
    projectId: 'cmsc23-project-juatco-maiso',
    storageBucket: 'cmsc23-project-juatco-maiso.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7EXPSlH7igkvqCRzOgRzRkohwjaWcPW8',
    appId: '1:57337771510:ios:903e08555a04961e20c3d7',
    messagingSenderId: '57337771510',
    projectId: 'cmsc23-project-juatco-maiso',
    storageBucket: 'cmsc23-project-juatco-maiso.appspot.com',
    iosBundleId: 'com.example.donationSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7EXPSlH7igkvqCRzOgRzRkohwjaWcPW8',
    appId: '1:57337771510:ios:903e08555a04961e20c3d7',
    messagingSenderId: '57337771510',
    projectId: 'cmsc23-project-juatco-maiso',
    storageBucket: 'cmsc23-project-juatco-maiso.appspot.com',
    iosBundleId: 'com.example.donationSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtR6VKFXGqT9YFIgiJlH-w2PR64gZcd2A',
    appId: '1:57337771510:web:833c1da942814e6f20c3d7',
    messagingSenderId: '57337771510',
    projectId: 'cmsc23-project-juatco-maiso',
    authDomain: 'cmsc23-project-juatco-maiso.firebaseapp.com',
    storageBucket: 'cmsc23-project-juatco-maiso.appspot.com',
    measurementId: 'G-48BBYXMDT1',
  );

}